### ISSUE TITLE
search for recipes page

### ISSUE THREAD

**Issue by mpilomthiyane97** [NokulungaM/DataForgeAI-Capstone-FullStack#19]
## Task Description
search recipe page

## Task Breakdown
- [x] #33
- [x] #32
- [x] #31

**Comment by mpilomthiyane97** [comment]
<img width="440" alt="recipe search" src="https://github.com/user-attachments/assets/1caa4b09-344b-4d4e-8b65-fd3c675f3009">

**Comment by ImisebenziEmihle** [comment]
On the latest commit for the search icon, please assist me with the modules error. Checkout search-icon branch.
