### ISSUE TITLE
Localhost3000 outputting Hogs assignment.

### ISSUE THREAD

**Issue by Nhlanhla-advocate** [NokulungaM/DataForgeAI-Capstone-FullStack#44]
I have coded the basic sign-up form structure, but when I npm start, the localhost3000 outputs an assignment which is the hogs assignment as opposed to the form coded. @KhileM @tech-chieftain  please advise. I will commit the code, but I won't merge it.

![Screenshot (321)](https://github.com/user-attachments/assets/31852bd9-b952-4412-b0dd-f30e998ae9ae)

**Comment by KhileM** [comment]
Solution has been provided therefore issue #44 is being closed.
