### ISSUE TITLE
DishDash as home link

### ISSUE THREAD

**Issue by Nhlanhla-advocate** [NokulungaM/DataForgeAI-Capstone-FullStack#46]
On the home page, please remove the 'Home' navbar and instead make DishDash as the home link. @NokulungaM 

![Home removed, title as home](https://github.com/user-attachments/assets/5ff8e2f8-4cd1-4787-9118-83ddd1ea0157)

**Comment by KhileM** [comment]
Completed by Nokulunga but no branch was created to link with this issue.
